# CI/CD Variables:
  # MASTER_SSH_USER, MASTER_HOST, CI_CONTAINER_REGISTRY, CI_SERVICES(Array), CI_STACK_NAME, CI_PROJECT_NAME, CI_PROJECT_ROOT

variables:
  MASTER_HOST: "hadido.ir"
  MASTER_SSH_USER: "root"
  MASTER_BRANCH: "main"
  CI_CONTAINER_REGISTRY: "registry.hadido.ir/hpds/memory-tracker/"
  CI_PROJECT_NAME: "memory-tracker"
  CI_PROJECT_ROOT: "/srv/memory_tracker"
  CI_SERVICES: "fastapi,nginx"
  CI_STACK_NAME: "memory-tracker"

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose --file=docker/Dockerfile/docker-compose.yml build --no-cache
    - bash docker/build_script.sh
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ssh ${MASTER_SSH_USER}@${MASTER_HOST} "
        cd ${CI_PROJECT_ROOT} &&
        git pull origin ${MASTER_BRANCH} &&
        bash -s < docker/deploy_script.sh ${CI_CONTAINER_REGISTRY} ${CI_PROJECT_ROOT} ${CI_PROJECT_NAME} ${CI_STACK_NAME} ${CI_SERVICES}
      "
  only:
    - main
